---
- name: setup Tomcat Server
  hosts: all
  become: yes

  tasks: 
  - name: install java on redhat
    yum: 
     name: java
     state: installed
    when: ansible_os_family == 'RedHat'

  - name: install java on debian
    apt: 
     name: default-jdk
     state: present
    when: ansible_os_family == 'Debian'

  - name: download Tomcat
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.100/bin/apache-tomcat-8.5.100.tar.gz
      dest: /opt

  - name: extract tomcat
    unarchive: 
      src: /opt/apache-tomcat-8.5.100.tar.gz
      dest: /opt
      remote_src: True

  - name: change permissions
    file: 
     path: /opt/apache-tomcat-8.5.100.tar.gz/bin/startup.sh
     mode: 0777

  - name: start tomcat
    shell: nonup ./startup.sh
    args: 
     chdir: /opt/apache-tomcat-8.5.100.tar.gz/bin
