---
- name: My Test playbook
  hosts: all
  become: true
  tasks:
  - name: stop httpd package
    service:
      name: httpd
      state: stopped 
  - name: remove httpd service now
    yum: 
      name: httpd
      state: removed 
